### ISSUE TITLE
Dual-screen devices with integrated trackpad and screen do not support multi-finger gestures（GDX1515）

### ISSUE THREAD

**Issue by sqlsec** [VoodooI2C/VoodooI2C#474]
**Describe the bug**
Dual-screen devices with integrated trackpad and screen do not support multi-finger gestures, like asus zenbook series's screenpad technology.In fact, it is a combination of a touchpad and a ScreenXpert screen.

using untouched latest VoodooI2C + VoodooI2CHID.  change this to 500
[https://github.com/VoodooI2C/VoodooI2CHID/blob/8182b1af40017645dd845935a912ecc465ee5057/VoodooI2CHID/Info.plist#L98](https://github.com/VoodooI2C/VoodooI2CHID/blob/8182b1af40017645dd845935a912ecc465ee5057/VoodooI2CHID/Info.plist#L98) 
The touchpad does work, and there are gesture animations in the settings, but it still only supports single-finger operation, just like a mouse

I recorded a short FingerMgmt's video: http://qiniu.sqlsec.com/fingermgmt.mp4

I tried under ubuntu and found that the touchpad screen display and touchpad multi-finger gestures under ubuntu are normal
So I guess this problem should be solved on Hackintosh, but I’m too silly

Under Ubuntu, the touchpad supports multi-finger touch：![](https://ae04.alicdn.com/kf/Hd1bdca4bb4924679b01f4a1cdca32e89b.png)
And the monitor also works normally under Ubuntu: ![](https://ae02.alicdn.com/kf/H65fa69aced174f478fc7d0f2bcb66a10m.png)

this is xinput command result under ubuntu 20.04:http://qiniu.sqlsec.com/ubuntu-20.04-xinput.log
this is dmesg log file under ubuntu 20.04: http://qiniu.sqlsec.com/ubuntu-20.04-dmesg.log

**Did you read the common errors documentation?**
yes

**Did you read the troubleshooting documentation?**
yes

**Have you searched the issue on Github, Gitter, or Google?**
yes

**System Environment**
Please answer:
1. What is your operating system? 
macOS Big Sur 11.5.2

2. What version of the drivers (including drivers) are you using?
the version is 2.6.5, use VoodooI2C + VoodooI2CHID

3. What is your hardware configuration?
ASUS ZenBook 14 UX434FLC i7-10510U+16GB+512GB

**Troubleshooting Archive**

[dmesg-2021-09-12-22-18.log](https://github.com/VoodooI2C/VoodooI2C/files/7153313/dmesg-2021-09-12-22-18.log)

This ioreg file is too big, This is the latest ioreg configuration file: http://qiniu.sqlsec.com/2021-09-12-22-16-IOReg.ioreg

If this file becomes invalid, I put it on my server:https://www.sqlsec.com/files/2021-09-12-22-16-IOReg.ioreg

**Additional context**

This issue has also been mentioned in the chat channel：https://gitter.im/alexandred/VoodooI2C
but it seems to be very complicated. You can only submit an issue on Github.

**Comment by M69W** [comment]
try v2.4.4 ?

**Comment by sqlsec** [comment]
@M69W Thank you for your answer, I will try it when I get home from get off work at night

**Comment by sqlsec** [comment]
@M69W v2.4.4 Still not working,Just like the latest version,change this to 500
https://github.com/VoodooI2C/VoodooI2CHID/blob/8182b1af40017645dd845935a912ecc465ee5057/VoodooI2CHID/Info.plist#L98
This touchpad can work,and there are gesture animations in the settings, but it still only supports single-finger operation, just like a mouse

**Comment by BradenJ6164** [comment]
I to have this issue. On ASUS Zenbook UX534. I am able to only get single clicks, no multi-touch.

**Comment by gvkt** [comment]
I think this is a problem with the architecture of the different event driver IOKit personalities in the kext with overlapping features when you have more than one device in the laptop with touch and/or mouse capabilities.

These laptops have a multi-touch screen (no mouse function) and a trackpad (mouse + multi-finger touch). Whether the trackpad has a display of its own is irrelevant, so screenpads shouldn't behave any differently.

The behavior depends on which event driver takes over the device. The related problem is that the same kext applies to both devices and so any change in the kext applies to both. There is no way to assign a particular event driver to one device and a different one to the other device. This has unintended consequences if the kext is modified.

Out of the box, the kext as downloaded works perfectly for the touch screen with multi-touch gestures. This is why the trackpad settings show the multi-touch gestures as Mac thinks this has a trackpad because of the touch screen not the trackpad.

But the default configuration of the kext makes the touchpad/screenpad not respond at all in my case as it works differently from the touch screen (as a precision trackpad) and VoodooI2CHIDDevice Touchscreen HID Event Driver which gets chosen for both Touch Screen and Trackpad is unable to process Trackpad events.

You can change that as suggested above by increasing the IOProbeScore for VoodooI2CHIDDevice Precision Touchpad HID Event Driver to give it priority over VoodooI2CHIDDevice Touchscreen HID Event Driver. This makes the former event driver take over both the touch screen (with some unintended consequences) and trackpad (which kind of works with single touch at the moment but doesn't work right as a mouse for clicks and does not work with multi-touch at least for this specific trackpad.

You can also force the kext to use the VoodooI2CHIDDevice Generic Mouse HID Event Driver for the trackpad to get full mouse functionality by deleting the touch sections or by increasing its IOProbeScore but that makes it take over the touch screen as well destroying its multi-touch capabilities.

So there are several separate issues here that needs to be addressed independently, not just single vs multi-touch which is a consequence but not the core problem.

1. How to assign the correct event driver for each device which are slightly different but with overlapping features. So, in this case there needs to be a way for VoodooI2CHIDDevice Touchscreen HID Event Driver to handle the touch screen as it now does OOB with the highest score but have either VoodooI2CHIDDevice Precision Touchpad HID Event Driver or VoodooI2CHIDDevice Generic Mouse HID Event Driver depending on need handle the trackpad. I don't see a way of doing this in a single kext as it exists. May be someone knows a way of doing this. The right solution may require a way to specify a flag to change IOProbeScore priorities differently for each discovered device within the same kext.

2. Have the proper trackpad Event Driver (with multi-touch and mouse functionality) handle the GDX1515 device correctly fixing any issues independent of the above. Right now, it seems to have a problem handling multi-touch.

From the little I know of this kext, this seems to be a kext architecture problem rather than the device or configuration problem.

Not sure if this is something the developers would consider rethinking and enabling for these types of laptops to work correctly. I request them to say if there is a work around or alternatively, an easy way for them to update the kext.

**Comment by sqlsec** [comment]
> 我认为这是 kext 中具有重叠功能的不同事件驱动程序 IOKit 特性的体系结构的问题，当您在笔记本电脑中有多个具有触摸和/或鼠标功能的设备时。
> 
> 这些笔记本电脑具有多点触控屏幕（无鼠标功能）和触控板（鼠标 + 多指触控）。触控板是否有自己的显示器无关紧要，因此屏幕板的行为不应有任何不同。
> 
> 行为取决于哪个事件驱动程序接管设备。相关的问题是相同的 kext 适用于两个设备，因此 kext 中的任何更改都适用于两者。无法将特定的事件驱动程序分配给一个设备，而将不同的事件驱动程序分配给另一台设备。如果 kext 被修改，这会产生意想不到的后果。
> 
> 开箱即用，下载的 kext 非常适合具有多点触控手势的触摸屏。这就是触控板设置显示多点触控手势的原因，因为 Mac 认为它有触控板，因为触摸屏不是触控板。
> 
> 但是 kext 的默认配置使触摸板/屏幕板在我的情况下根本没有响应，因为它的工作方式与触摸屏（作为精密触控板）和 VoodooI2CHIDDevice 触摸屏 HID 事件驱动程序不同，为触摸屏和触控板选择了无法处理触控板事件。
> 
> 您可以通过增加 VoodooI2CHIDDevice 精密触摸板 HID 事件驱动程序的 IOProbeScore 使其优先于 VoodooI2CHIDDevice 触摸屏 HID 事件驱动程序来更改上述建议。这使得以前的事件驱动程序同时接管了触摸屏（有一些意想不到的后果）和触控板（目前可以使用单点触摸，但不能像鼠标一样用于点击，也不适用于多点触摸至少对于这个特定的触控板。
> 
> 您还可以强制 kext 为触控板使用 VoodooI2CHIDDevice 通用鼠标 HID 事件驱动程序，通过删除触摸部分或增加其 IOProbeScore 来获得完整的鼠标功能，但这会使其接管触摸屏并破坏其多点触控功能.
> 
> 所以这里有几个单独的问题需要独立解决，而不仅仅是单点触控和多点触控，这是一个结果，而不是核心问题。
> 
> 1. 如何为每个略有不同但具有重叠功能的设备分配正确的事件驱动程序。因此，在这种情况下，需要有一种方法让 VoodooI2CHIDDevice 触摸屏 HID 事件驱动程序来处理触摸屏，因为它现在以最高分执行 OOB，但根据需要具有 VoodooI2CHIDDevice 精密触摸板 HID 事件驱动程序或 VoodooI2CHIDDevice 通用鼠标 HID 事件驱动程序处理触控板。我没有看到在单个 kext 中这样做的方法，因为它存在。可能有人知道这样做的方法。正确的解决方案可能需要一种方法来指定一个标志，以便为同一 kext 中的每个发现的设备以不同的方式更改 IOProbeScore 优先级。
> 2. 让适当的触控板事件驱动程序（具有多点触控和鼠标功能）处理 GDX1515 设备，正确修复与上述无关的任何问题。现在，处理多点触控似乎有问题。
> 
> 从我对这个kext的了解来看，这似乎是一个kext架构问题而不是设备或配置问题。
> 
> 不确定这是否是开发人员会考虑重新考虑并使这些类型的笔记本电脑正常工作的事情。我要求他们说是否有解决方法或替代方法，让他们更新 kext。

@ben9923

**Comment by gvkt** [comment]
I thought I found a way for 2 above with the property match feature of the kext but it doesn't work as expected. Don't know if this is a bug or a feature.

With OOB kext, the same Touch Screen Event driver attaches to both touch screen and the GDX1515 since they are both I2C devices and both respond to touch and the touch screen event driver has the highest priority of the lot. This makes the touch screen work correctly but doesn't respond to the GDX1515 trackpad at all. 

If I use the property match on the VoodoI2CHIDDevice to match name ELAN2008 (the touch screen in my case), it works fine for the Touch Screen as before and nothing gets loaded for the trackpad with name GDX1515. This is as one would expect. But we need a driver for the trackpad to make it work. Preventing the touch screen driver to attach to the trackpad should make it pick the other available personalities which at least respond to input. This is what happens to the trackpad when the score is changed to 500 for the Precision trackpad as suggested above except this happens to touch screen as well losing its touch screen functionality.

I had hoped introducing a property match in the VoodoI2CHIDDevice Touch Screen Event driver to look for ELAN2008 would prevent it from attaching to the trackpad and allow it to attach only to the touch screen which is named ELAN2008.

Unfortunately, including this property match in that section makes that personality unavailable to attach to either device. In other words, nothing seems to match what is specified in that section (I Thought it would work the same way as the synaptics driver included there with a property match for name). Don't know if this is a bug or a feature that I don't understand.

If somehow just the generic VoodooI2C event driver can be attached to the trackpad while the touch screen event driver is attached to the touch screen, it would at least make the trackpad behave correctly as a single finger mouse. While GDX1515 does not seem to be supported as a trackpad without odd behavior even for single touch, the mouse part seems to be common to all devices. Is there any way to make this differential assignment happen with the kext based on the names of the devices mentioned above?

To summarize for the GDX1515 device:
Attached to 
Touch screen event driver: No response to input single finger or not
Multi Touch or Precision Trackpad event drivers: Acts kind of like a single mouse but with odd behavior for clicks (doesn't work as left and right mouse buttons).
Just VoodooI2CHIDDevice :  Acts correctly like a mouse with single finger cursor movement and clicks with left and right clicks working as it should.

1. Is there a simple way to include the correct behavior for the GDX1515 device in the kext itself to correctly support that device (should be similar to supporting elan and synaptics separately)? Understand that this may not be a priority for developers.

2. Is there a way to use Property Match to force a specific personality from the kext to attach to a device based on its name while preventing the same personality from attaching to another device with a different name and instead have a different personality attach to it?

Thanks

**Comment by kprinssu** [comment]
@sqlsec Please use English to reply.

**Comment by ben9923** [comment]
@sqlsec @gvkt Can you get HID driver logs from your machines using Linux?
I'd like to see if there's something unique in there.

Not sure how to do it exactly.

**Comment by gvkt** [comment]
Unfortunately, I don't have a Linux installation on this laptop. But can try it out in a couple of weeks. Will post if @sqlsec hasn't been able to get this.

The problem of handling two different screen devices with different event drivers can be handled with the Property match solution (using Product ID) so that is no longer a factor for multi-touch not working on the GDX track/touch/screenpad. We should focus on just getting the GDX1515 device to work correctly. Whether it has a screen associated with it also seems irrelevant.

The touchpad functionality in the Screenpad (GDX1515) isn't handled correctly by the Precision Touchpad event driver in this kext even though it is supposed to be a I2C HID device.

Perhaps the logs from the Linux drivers will help here.

Single finger cursor movement and taps work. The clicks are the problem. They seem to be sending events somewhat different from a left or right mouse clicks and only work accidentally as a single mouse click depending on where it is clicked. Multi-touch of course is not working.

**Comment by sqlsec** [comment]
@ben9923 Excuse me,How can l get HID driver logs from your machines using Linux? I will fully cooperate with your work

**Comment by gvkt** [comment]
@ben9923
I may have found a **possible** reason for this GDX1515 trackpad not working for multi-touch looking at some Linux discussions. Would like your opinion on whether this may explain VoodooI2CHID PTP driver only seeing this device as a single touch mouse.

From what I understand, there is a specific start-up initialization requirement for these trackpads made by Goodix even if they are I2C-HID compliant.

They can operate in a legacy mouse mode or a Precision Trackpad mode. On power-up, they default to legacy mouse mode. They can be put into PTP mode by sending a I2C SET_OR_SEND_REPORT command. However, the latter command must not be sent within 60ms of the I2C SET_POWER ON for the device, otherwise the command will be dropped and the switch to PTP mode will not happen. Apparently, the Linux boot process will provide enough of a delay between I2C probe and HID initialization to not make this an issue but in a S2 suspend and resume scenario, it may happen with less than 60 ms delay between the two and so the track-pad was observed to wake up as a legacy mouse.

From your knowledge of the Voodoo code, 

1. Is there an appropriate SET_OR_SEND_REPORT command sent during HID initialization to make it transition to PTP mode?
2. If so, is it possible that it is sent too quickly after the i2c probe being sent earlieri (i.e., < 60ms)

If you believe the above might be a possible explanation, we can test it by introducing a sufficient delay before HID initialization.

If anyone has the time and the knowledge of the code already to quickly add this delay hack for testing before the command is sent to make it switch to PTP, I am happy to test on my machine. It would take a very long time for me to learn and create the build environment and to understand the Voodoo code sufficiently to place this delay and generate the compiled kexts.

**Comment by sqlsec** [comment]
@gvkt @ben9923 Thank you for your ideas, let me try to manually change the sleep delay to see, wait for my good news : )

**Comment by kprinssu** [comment]
@sqlsec Please avoid spamming the Github ticket. If you have nothing to contribute, please don't post.

**Comment by sqlsec** [comment]
@ben9923 @gvkt @kprinssu Thank you for your ideas. I found this discussion about this trackpad in the Linux community at: https://bugzilla.kernel.org/show_bug.cgi?id=204991

According to this idea, I tried to use Xcode to compile the project myself. I feel that the main code is in this file https://github.com/VoodooI2C/VoodooI2CHID/blob/master/VoodooI2CHID/VoodooI2CPrecisionTouchpadHIDEventDriver.cpp

I tried to increase the IOSleep delay before entering the enterPrecisionTouchpadMode() function. I was too weak. I added several IOSleep, but it didn’t seem to be successful. Is it a problem with my operation? Is it still missing the reason for SET_OR_SEND_REPORT?

**Comment by gvkt** [comment]
Looks like that delay change for the Linux has become moot as the current drivers simply disable real time power management for a Goodix device (controlled by a quirk flag). These devices appear to be flaky otherwise. The tiny power savings by not doing the power management (sending device to sleep etc) is held as not compelling enough to justify the finicky behavior. If VoodooI2C is doing real time power management, that may be a good solution when it encounters these devices.

@sqlsec I was also able get the source code into  Xcode and compile to get a kext that behaves the same as the release version.

There is code in the linked driver to switch to PTP mode.

I have been wholly unsuccessful in instrumenting the code to determine whether the switch happens (or even whether  that method os even reached). Just can't get the IOLog to work. Don't see anything in system logs. Only way I can see the debug output logs is via dmesg. 

Tried to compile with a lot of instrumentation via IOLog to get a feel for what is happening and when. But none of those statements seem to output anything. So not even sure what path the VoodoI2C code takes in the initialization process and whether it ever executes the switch mode method.

So, without some active guidance/help from the developers of the existing code . I am at a dead end.

**Comment by gvkt** [comment]
**Side note:** For anyone that stumbles on this with web search, logs can be seen by manually loading the Voodoo kexts rather than via Opencore/Clover injection. Don't know the reason for this or whether there is a fix for the latter. But if anyone is building VoodooI2C kexts with their own instrumentation, remove them from injection at boot and load it manually from the directory where they are generated via kextutil -d VoodooI2C.kext <satellite kext>. Since the kexts are unsigned, you will need to disable SIP and in Big Sur you will need to allow them to be loaded via Setup security preferences and reboot every time you compile. The kexts also should have root:wheel permissions to load. A very long and painful process.

As to the topic of this thread in hand, the decision of whether the device is under Power Management seems to be upstream from the VoodooI2C. The Linux solution is to completely disable PM for this device. These kexts don't seem to control that. They just register for callbacks on power state changes to do what may be necessary. Introducing more delay between power on and switching to PTP mode does not seem to make a difference.

I have managed to instrument the code to output the reports received from the device (GDX1515) as the single touch is working. Trying to study the reports and see whether they make sense and consistent with reports sent by the working Elan touch screen for finger movements. And what happens with multi-touch.

There is also a problem with clicks. There is no left vs right click, just one click and that click seems to be interpreted as a non-primary click. While it works as a left click in most of the use cases, it seems to create some contextual popups in other cases (different from a right click).

I will post my findings rather than just dump the output and ask others to look through them. I am yet to find a clear document of how to parse the PTP collection input report, so it may take a while.

None of the interrupts also seem to work for GPIO pinning this device. Several pin numbers seem to get Voodoo to register for the hardware number without error but no interrupts are received for this device and so even the reset times out. So using polling method.

This is one awful problematic trackpad. Should probably be blacklisted as Hackintosh-unfriendly.

**Comment by gvkt** [comment]
For future reference some data about the GDX1515.

The parsed report descriptor provided by the device is attached

[GDX1515_RD.txt](https://github.com/VoodooI2C/VoodooI2C/files/7668719/GDX1515_RD.txt)

Sample report excerpts provided by the device for touch actions in my instrumented code look like the following. According to the report descriptor, this seems to conform to this section in the descriptor

```
0x05, 0x0D,        // Usage Page (Digitizer)
0x09, 0x05,        // Usage (Touch Pad)
0xA1, 0x01,        // Collection (Application)
0x85, 0x11,        //   Report ID (17)
0x05, 0x0D,        //   Usage Page (Digitizer)
0x09, 0x22,        //   Usage (Finger)
```

Single left click:

> 11  3 3f  1 5d  6  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0 7d 50  1  0  0
...

Single right click:

> 11  3 c7  a 4f  7  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0 51 d2  1  0  0
...

Single finger swipe:

> 11  3 c9  3 e7  2  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0 bf 64  1  0  0
...

Two finger swipe:

> 11  3 c6  2 a6  4  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0 31 a3  1  0  0 
> 11  3 c6  2 a6  4  7 e9  2 cd  1  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0 c7 a3  2  0  0
...

Looks like the first finger touch info report followed by two finger info report.

But this is not being interpreted as multi-touch. I don't have a clue yet as to why and whether this is compliant with HID specs.

If anyone has some insight into this, feel free to chime in while I plod through learning the details of the protocol.

**Comment by gvkt** [comment]
@ben9923 
After analyzing the runtime flow, here is an explanation of why multi-touch isn't working with the current VoodooI2C driver code for this Goodix screenpad GDX1515 which appears to be working fine as a multi-touch precision trackpad consistent with Microsoft's reporting as a PTP HID device.

I don't have enough of an understanding of the concepts as yet to figure out where the fault lies or what should change. This is simply a diagnosis of why it fails to work in the current kext code.

1. The screenpad being detected and set up as a IOHIDDevice is more or less working as it should with the ability to configure and get input reports over I2C. There are some lifecycle/power management glitches (dead on wakeup, e.g.) which needs to be looked at but this is an independent issue for a later time.
2. The issue of polling vs interrupts is another independent issue that I am leaving aside for now.
3. VoodooI2CPrecisionTouchpadHIDEventDriver is the driver to be used for this IOHIDDevice (not VoodooI2CTouchscreenHIDEventDriver) and when a laptop has both a touch screen and this PTP trackpad, it requires some product ID matching to set up the appropriate drivers to attach to each as described in earlier post.
4. VoodooI2CPrecisionTouchpadHIDEventDriver is a simple wrapper around VoodooI2CMultitouchHIDEventDriver for initialization and power management and fine for the purpose of setting up the precision trackpad (except perhaps for the issue of waking up to be looked at later). The reports from the instrumented code in the previous post shows that the device is indeed working in a PTP mode after boot/initialization.
5. The input report from this device is quite simple and appears to be consistent with Microsoft's requirements (it is certified as a PTP under the Microsoft program). Reference: https://docs.microsoft.com/en-us/windows-hardware/design/component-guidelines/windows-precision-touchpad-implementation-guide
6. The record for touch input reporting is 31 bytes (after stripping the size bytes). 1 byte for report type ID which is always 0x11 for PTP mode, followed by 5 items of 5 bytes each for each finger (4 bytes of X and Y and a leading byte for additional info such as TIP switch, etc), followed by 2 bytes for timing information and a byte for touch count in this record (how many fingers have touch data in the report with rest zeroed). The purpose of remaining last two bytes is not clear to me. They are always zero in my use cases tested so far.
7. The fact that this reporting works correctly as a single finger device shows that the parsing and use of this reporting is fine for the first finger quintet usage.
8. So, why is the additional finger data ignored for multi-touch? The explanation is in the code logic for VoodooI2CMultitouchHIDEventDriver (which works fine as a super class for VoodooI2CTouchscreenHIDEventDriver for my touch screen).
9. VoodooI2CMultitouchHIDEventDriver is set up as a subclass of IOHIDEventService (which needs to be looked at going forward as the latter is deprecated in favor of using IOUserHIDEventService). The problem is in the static vs dynamic value population of the elements of a report.
10. In the current implementation, VoodooI2CMultitouchHIDEventDriver gets the supported elements for the device as part of the initialization and caches those element objects. The assumption is that the objects cached for these elements dynamically update their respective values as new reports come in. This caching is done in VoodooI2CMultitouchHIDEventDriver::parseElements() and parseDigitizerElement(). The problematic one is the element digitiser.contact_count (which in theory should maintain the current contact count as each new report comes in and works for the touch screen as it should).
11. But during the operation of this device, the value in that element always remains at zero as new reports come in (I am not clear as to who forces this value update for new input reports each of which has the current contact count as part of the record).
12. Because of this, in the processing of each input report in VoodooI2CMultitouchHIDEventDriver::handleInterruptReport, the event count is always set to zero in creating the VoodooI2CMultitouchEvent object and so this flows through the subsequent VoodooI2CMultitouchInterface and VoodooI2CNativeEngine with no action taken. 
13. It is not clear to me who actually does the single finger action as observed but the above is an explanation of why multi-touch is ignored.

Side note: In the IOUserHIDEventService model, the getElements should be explicitly called as each report is received to force the values of the element objects to be updated for the current report but I don't understand the IOHIDEventService based model enough to see if this explicit update forcing is needed.

**Comment by sqlsec** [comment]
> @ben9923 在分析了运行时流程后，这里解释了为什么多点触控不能与当前的 VoodooI2C 驱动程序代码一起使用这个 Goodix 屏幕板 GDX1515，它似乎作为多点触控精确触控板工作正常，与微软的报告一致PTP HID 设备。
> 
> 我对这些概念的理解还不够，无法弄清楚错误在哪里或应该改变什么。这只是对为什么它无法在当前 kext 代码中工作的诊断。
> 
> 1. 被检测并设置为 IOHIDDevice 的屏幕板或多或少地工作，因为它应该具有通过 I2C 配置和获取输入报告的能力。有一些生命周期/电源管理故障（例如，在唤醒时死亡）需要查看，但这是以后的独立问题。
> 2. 轮询与中断的问题是我暂时搁置的另一个独立问题。
> 3. VoodooI2CPrecisionTouchpadHIDEventDriver 是用于此 IOHIDDevice（不是 VoodooI2CTouchscreenHIDEventDriver）的驱动程序，当笔记本电脑同时具有触摸屏和 PTP 触控板时，它需要一些产品 ID 匹配来设置适当的驱动程序以附加到前面的帖子中所述的每个驱动程序。
> 4. VoodooI2CPrecisionTouchpadHIDEventDriver 是 VoodooI2CMultitouchHIDEventDriver 的一个简单包装器，用于初始化和电源管理，并且很好地用于设置精确触控板（除了稍后要查看的唤醒问题）。上一篇文章中检测代码的报告显示，设备在启动/初始化后确实在 PTP 模式下工作。
> 5. 这个设备的输入报告非常简单，看起来符合微软的要求（它被认证为微软计划下的PTP）。参考：[https](https://docs.microsoft.com/en-us/windows-hardware/design/component-guidelines/windows-precision-touchpad-implementation-guide) : [//docs.microsoft.com/en-us/windows-hardware/design/component-guidelines/windows-precision-touchpad-implementation-guide](https://docs.microsoft.com/en-us/windows-hardware/design/component-guidelines/windows-precision-touchpad-implementation-guide)
> 6. 触摸输入报告的记录为 31 个字节（剥离大小字节后）。1 个字节用于报告类型 ID，对于 PTP 模式始终为 0x11，然后是每个手指的 5 个项目，每个项目 5 个字节（X 和 Y 的 4 个字节以及附加信息（如 TIP 开关等）的前导字节），然后是 2此记录中用于计时信息的字节和用于触摸计数的字节（报告中有多少手指有触摸数据，其余部分归零）。我不清楚保留最后两个字节的目的。到目前为止，在我测试的用例中，它们始终为零。
> 7. 该报告作为单指设备正确工作的事实表明，该报告的解析和使用对于第一指五重奏使用来说是良好的。
> 8. 那么，为什么多点触控会忽略额外的手指数据？解释在 VoodooI2CMultitouchHIDEventDriver 的代码逻辑中（它可以作为 VoodooI2CTouchscreenHIDEventDriver 的超类用于我的触摸屏）。
> 9. VoodooI2CMultitouchHIDEventDriver 被设置为 IOHIDEventService 的子类（需要进一步研究，因为后者已被弃用，而支持使用 IOUserHIDEventService）。问题在于报表元素的静态与动态值填充。
> 10. 在当前的实现中，VoodooI2CMultitouchHIDEventDriver 获取设备支持的元素作为初始化的一部分并缓存这些元素对象。假设为这些元素缓存的对象会随着新报告的出现动态更新它们各自的值。这种缓存是在 VoodooI2CMultitouchHIDEventDriver::parseElements() 和 parseDigitizerElement() 中完成的。有问题的是 digitiser.contact_count 元素（理论上，它应该在每个新报告出现时保持当前的联系人计数，并且应该在触摸屏上正常工作）。
> 11. 但是在此设备的操作期间，该元素中的值在新报告出现时始终保持为零（我不清楚谁强制对新输入报告进行此值更新，每个报告都将当前联系计数作为报告的一部分记录）。
> 12. 因此，在处理 VoodooI2CMultitouchHIDEventDriver::handleInterruptReport 中的每个输入报告时，在创建 VoodooI2CMultitouchEvent 对象时事件计数始终设置为零，因此这会流经后续的 VoodooI2CMultitouchInterface 和 VoodooI2CNativeEngine 而不采取任何行动。
> 13. 我不清楚谁实际执行了观察到的单指操作，但以上解释了为什么忽略多点触控。
> 
> 旁注：在 IOUserHIDEventService 模型中，应该在收到每个报告时显式调用 getElements 以强制为当前报告更新元素对象的值，但我对基于 IOHIDEventService 的模型的了解不够，无法查看这是否显式需要更新强制。

Thank you for the clues and ideas you provided these days. Today I finally solved the multi-finger touch problem of the touchpad based on the ideas you provided. :

![QQ20211209-0](https://user-images.githubusercontent.com/25379234/145340663-e64b70e1-760f-4cf3-af68-efb25ad9c98c.jpg)

**Comment by sqlsec** [comment]
@ben9923 @gvkt @ben9923  
I mainly modified this file: https://github.com/VoodooI2C/VoodooI2CHID/blob/master/VoodooI2CHID/VoodooI2CMultitouchHIDEventDriver.cpp

Deleted related code related to `kHIDUsage_Dig_TouchScreen`

Then recompile a new one, and then delete this part of the code in info.plist:
```xml
<key>VoodooI2CHIDDevice Touchscreen HID Event Driver</key>
<dict>
...
</dict>
```
Here is the file I compiled:

[VoodooI2CHID.kext.zip](https://github.com/VoodooI2C/VoodooI2C/files/7682514/VoodooI2CHID.kext.zip)

My loading sequence is for your reference:

![顺序](https://user-images.githubusercontent.com/25379234/145341259-67493240-19a7-4cc8-992d-2ac4f912b001.png)

At present, this repair method feels that it will damage other devices, so I will consider submitting a compatible PR in the near future. Wait for my good news, thank you

**Comment by shiecldk** [comment]
@sqlsec @gvkt That's great news. Does multitouch work on both the screenpad and the main touchscreen?

**Comment by kprinssu** [comment]
@sqlsec Please create a PR, Ben and I will review it there.

**Comment by gvkt** [comment]
@sqlsec that is good to hear. Can you please post the code changes here for quick review/testing with actual device rather than the compiled kext? Sooner the better so I can test it on actual device before you create a PR.

I do not believe tearing out TouchScreen driver personality/related code should be part of the solution as it will cripple the touch screen if the laptop also has one. This will have the same effect as increasing the probe score for Multitouch driver to let that attach to a touch screen instead which will turn the touch screen into a giant trackpad not a touch screen (the cursor movements will be absolute in latter and relative to current cursor position in the former for example).

If what you have identified is fixes in the shared Multi-touch event driver to make multi-touch trackpad work, then any fixes should preserve the current proper functioning of the touch screen.

Thanks

**Comment by gvkt** [comment]
> @sqlsec @gvkt That's great news. Does multitouch work on both the screenpad and the main touchscreen? Does your display on the screenpad still work?

From what I have seen analyzing the Screenpad, nothing done in these kexts will affect the screenpad video part which MacOS will see as a second display in the graphics code (and that can be independently turned off or on in the port configuration). However, there is a logical functionality problem in how to use the screenpad - as a second touch screen with display or as a trackpad for the main screen- as far as touch is concerned. It cannot be simultaneously both. This is why your Pro Duo has an additional non-screen trackpad in addition to the second display. The Pro with the single screen has a screenpad that can switch between a second touch screen and a trackpad in software.

As a second touch screen the touch screen even driver functionality is required which already works with the touch screen driver attached to both. For use as a trackpad for both screens, the trackpad functionality is needed which will affect movement based on which screen is current one. They are not the same. Detecting multi-touch is only half the story.

The windows implementation has solved this by giving a switch option between the two both with Fn key as well as creating a trackpad overlay mode in software while in the Screenpad mode. This will be far beyond the scope of these touch kexts.

**Comment by gvkt** [comment]
I think I found the root cause of the problem and why ripping out TouchScreen worked for @sqlsec 

he problem is the following code in VoodooI2CMultitouchHIDEventDriver::parseElements

>if (element->conformsTo(kHIDPage_Digitizer, kHIDUsage_Dig_Pen)
            || element->conformsTo(kHIDPage_Digitizer, kHIDUsage_Dig_TouchScreen)
            || element->conformsTo(kHIDPage_Digitizer, kHIDUsage_Dig_TouchPad)
            || element->conformsTo(kHIDPage_Digitizer, kHIDUsage_Dig_DeviceConfiguration)
            )
            parseDigitizerElement(element);
        }

isn't safe if a device can act as both a touch screen and a touchpad. When parsing the elements from the record descriptor using the above code, the elements like contact count can appear in both the TouchScreen section and the TouchPad section. Depending on the order in which the records are processed, the cached can object can refer to the one for TouchScreen (as it appears to be happening here) or for TouchPad. So, when Touchpad usage input reports come in with the device acting as a trackpad, that object is not updated (i.e., it is pointing to the wrong object for the mode in which the device is).

A clean solution would factor out and parametrize this code depending on whether it is coming from a TouchScreenEventDriver or PrecisionTrackPad (or pen event driver) and test only for conformance to that usage.

This should fix the problem without tearing up the touchscreen functionality.

Y'all welcome.... :)

**Comment by kprinssu** [comment]
Great find @gvkt, please create a PR!

**Comment by shiecldk** [comment]
@gvkt @kprinssu Is it possible to add a boot-arg or an external app to decide whether to set the ScreenPad as touchpad or touchscreen? e.g. for my UX582 it might be better to set the ScreenPad as a touchscreen for the most case, and perhaps switch it to touchpad if I need it as touchpad. For @gvkt and @sqlsec 's cases, it would be the other way - set the ScreenPad as a touchpad for the most case, and switch it to touchscreen if they need it.

**Comment by gvkt** [comment]
Might be a bit premature to create a PR.

For a laptop like mine with both TouchScreen and Screenpad, there is still need for a general way to attach the PTP driver to the trackpad and the touchscreen driver to the touch screen. This does not happen OOB. This cannot be done with probe score twiddling. Without that exact assignment the fix above would be moot. Right now, I have a hardwired hack in info.plist to check for the product id property for both Touch screen driver and Precision track driver personalities.

Also, the buttons aren't working correctly yet on this trackpad. There is no left or right click. Clicking anywhere sends some weird sequence that can act as left click in contexts where the sequence is ignored or has weird responses. For example, clicking on a folder in Finder with trackpad brings up this popup as shown in the image below rather than open the folder to show its contents listing with a left click. Click and drag doesn't work because of it.

<img width="687" alt="Screen Shot 2021-12-10 at 8 36 42 AM" src="https://user-images.githubusercontent.com/11695893/145611706-b09ec35d-a903-4724-ad1a-3d426808a7b4.png">

Meanwhile, here is the diffs list for minimal changes that restored the full multi-touch capability to the Goodix screenpad to act as a touchpad without affecting the use of Touch Screen driver for the main screen (with the caveat that the Info.plist change here is specific to the product IDs of the trackpad and touch screen on my laptop).

[VoodooDiff.txt](https://github.com/VoodooI2C/VoodooI2C/files/7694301/VoodooDiff.txt)

There might be other solutions to achieve the same thing.

**Comment by gvkt** [comment]
> @gvkt @kprinssu Is it possible to add a boot-arg or an external app to decide whether to set the ScreenPad as touchpad or touchscreen? e.g. for my UX582 it might be better to set the ScreenPad as a secondary touchscreen for the most case, and perhaps switch it to secondary touchpad if I need it as touchpad. For @gvkt and @sqlsec 's cases, it would be the other way - set the ScreenPad as a touchpad for the most case, and switch it to touchscreen if they need it for that case.

Without the need to switch on the fly, my hack to use product ID matching for each personality works but requires Info.plist editing.

There needs to be a clean and generalized solution to assign a specific driver to a specific device or the mode in which you want that device to function.  That would be related to the above requirement. Whether you can change the mode on the fly is an additional feature.

Looking at the current architecture, a clean way to do it with minimal perturbation is to write a single HID driver class that attaches to any I2C HID device (rather than each of the satellite personalities vying for that spot based on some scoring which is fragile with unintended consequences when you have multiple touch devices and/or multiple device modes). This wrapper class would front-end the OS interactions - start function, power management, parsing the descriptors for a device once and keeping a list for each of the different "personalities" of the device and route the handleReports to the appropriate handler (which corresponds to the current satellite personalities). It should be possible to write this wrapper to be extensible for new types of devices or products. This is necessary I think anyway for future (at least as far as future of Hackintosh exists).

I am not sure this work is worth it without doing a switchover to IOUserHIDEventService from the deprecated IOHIDEventService although that would make Catalina minimum OS supported. Tough call.

Then the real time mode change can be seen as a way to affect a configuration used by this wrapper class which uses the dynamic routing to each of the handlers to make that switch. I don't know the system architecture well enough to say if that mode change can be affected by a function key or a keyboard shortcut, etc.

I don't think this is a quick fix though.

**Comment by shiecldk** [comment]
@gvkt Thanks for the info. Could you attach the kext and files you edited? I'm gonna try if it works with my setup today.

**Comment by gvkt** [comment]
> @gvkt Thanks for the info. Could you attach the kext and files you edited? I'm gonna try if it works with my setup today. (Just reinstalled macOS; haven't setup my compiler environment)
> 
> Is this everything you edited?
> 
> > [VoodooDiff.txt](https://github.com/VoodooI2C/VoodooI2C/files/7694301/VoodooDiff.txt)

Yes. Here are the five edited source files corresponding to that diff along with release builds of the two kexts.
[ChangedFilesAndKexts.zip](https://github.com/VoodooI2C/VoodooI2C/files/7696789/ChangedFilesAndKexts.zip)

The Info.plist from VoodooI2CHID.kext WILL need to be changed to "pin" the required drivers to your devices using the product ID in your laptop. Anyone downloading this, DO NOT use the kexts as-is without editing Info.plist for the product ids on your laptop.

This Info.plist edit is required only if the trackpad is attached to the TouchScreenEventDriver OOB. If it is attached to the PrecisionTrackpad driver and the touch screen(s) are attached to the TouchScreen driver OOB then you don't need to change the original Info.plist

However, with two touch screens in the duo, you MAY have problems with the current logic in the kexts that may not be solved by my fixes which is only to fix the handling of the trackpad and that should fix your trackpad for multi-touch. If the two screens are working correctly as touch screens without issues OOB, then you are all set.

**Comment by gvkt** [comment]
The click issue is solved with settings for the Trackpad. Turns out if the Forced Click and Haptic Feedback is checked, a click on this trackpad is always interpreted as a forced click. Not sure if this is a bug or feature. But since Haptic feedback is not available on this trackpad as far as I know, I simply unchecked it and now clicks and taps work as they should. So, I have a fully functional trackpad now!

**Comment by shiecldk** [comment]
@gvkt I tried you patch on my UX582. Unfortunately, it looks like my screenpad still receive one finger input only if I set its productID under VoodooI2CTouchscreenHIDEventDriver and it receive no finger input if I set is productID under VoodooI2CPrecisionTouchpadHIDEventDriver. Any ideas on how to fix this? Have you tried set you screenpad's productID under VoodooI2CTouchscreenHIDEventDriver?

**Comment by ben9923** [comment]
@gvkt Great work :)
Would you mind pushing the code to a fork for easier review, suggesting changes, etc.?

I would like to find a way to merge this in. If it works on Linux, it should work with VoodooI2C as well.

**Comment by gvkt** [comment]
@shiecldk Using the release version of the kexts from this site without any patches or changes, post the device names (ETPD, TPL0, etc) of your three touch devices, their vendor and product IDs (properties of VoodooI2CHIDDevice under the device name for each) and what event drivers get attached to which device (below the IOHIDinterface) using IORegistryExplorer after the kexts have loaded. Again this is with the kexts available on this site with no changes. The problem to be solved will be apparent from that and easier to discuss.

There are potentially two separate problems being solved here. 

One, that the appropriate event drivers are being attached to the device corresponding to the function mode you need from them (as precision trackpads or touch screens). This is independent of the source code changes and is achieved from changes to the Info.plist alone using property match and/or IOProbeScore as necessary. This needs to be done first and you need to understand what is being done here and how. Your laptop may or may not have a problem in this part to fix. What you would need to ensure is that the Precision Trackpad event driver is loaded for the trackpad and the TouchScreen event driver is loaded for both of your touch display screens.

Two, once the appropriate event drivers are attached to each of the devices, the code is parsing the report descriptors correctly for the one that is not providing the required multi-touch behavior because of the code snippet issue I posted as the root cause. The presence of three devices might require a slightly different source code change.

It is easier if we can establish the problem to be solved and the default configuration for your laptop before applying a solution.

**Comment by gvkt** [comment]
> @gvkt Great work :) Would you mind pushing the code to a fork for easier review, suggesting changes, etc.? I would like to find a way to merge this in. If it works on Linux, it should work with VoodooI2C as well.
> 
> I'll have a proper look this week.

Will do. I realized while my changes have made it work for my laptop, it requires a similar source change to the TouchScreenEventDriver source code as well (like the one I have for PrecisionTrackpadEvent driver to override parseElements and call super's parseElements with its usage mode) to make it agnostic to the order in which the touch screen and trackpad sections appear in the report descriptor.

I suspect this change will likely be necessary to fix the problem  @shiecldk is facing. So, I will create a fork after the solution is generalized to cover that case as well.

**Comment by shiecldk** [comment]
@gvkt Thanks again. The trackpad is ETPD with ProducID: 0x3101 VendorID: 0x4f3. The main touchscreen is TPL0 with ProducID: 0x2c56 VendorID: 0x6113. The screenpad is TPL1 with ProducID: 0x2c23 VendorID: 0x6113.


These are the result:
For the original kext files from your post, none of the device is working, and I got this in IOReg:
<img width="1202" alt="IOReg_Incorrect_ProductID" src="https://user-images.githubusercontent.com/42949962/145731054-0adf69a1-adab-4cff-a1a6-e0819d68e74a.png">

After changing the ProductID, I got this, which is the same as the original VoodooI2C kexts without your mod:
<img width="1202" alt="IOReg_Correct_ProductID" src="https://user-images.githubusercontent.com/42949962/145731061-82c38cec-ec99-4016-a3a6-9e88fda490fa.png">

**Comment by gvkt** [comment]
The driver assignment in the second image is what you want to happen. So, if the original Voodoo kexts give you that assignment then you don't need the Info.plist mods that I had to do. This part has nothing to do with the single vs multi-touch issue.

Use the two kexts in this zip file **after replacing the Info.plist in VoodooI2CHID** with the one in the original or whatever changes you made to get the assignment in your second image.
[VoodooMod.zip](https://github.com/VoodooI2C/VoodooI2C/files/7700166/VoodooMod.zip)

This makes symmetrical changes to TouchScreen event driver as for the Precision Trackpad event driver to remove interference from any other modes the device may be capable of.

Before looking at touch, ensure that the assignments are as shown in your second image after using the kexts in this post.

If this solves the single vs multi-touch problem for TPL1 (which is where I assume is the problem you are trying to solve), then it was due to the same root cause as identified in mine. If not, then there is a different root cause and you will have to do the same debugging as I did with instrumented code to figure out why after setting up your Xcode environment.

If the multi-touch works with these kexts for Screenpad, see if there are any side-effects on any of the devices such as stylus not working, etc which may require a different mod.

**Comment by shiecldk** [comment]
@gvkt Excellent! You are my hero. These kexts with my Info.plist mod solves multitouch issue of my ScreenPad! Multitouch is working on all of my devices now. Will do more test to see if there is any other problems.

**Comment by gvkt** [comment]
@ben9923 I have created a fork of VoodooI2CHID at
https://github.com/gvkt/VoodooI2CHID
with the source code fixes. The Info.plist is not changed from original, so it assumes the correct event drivers are attached if there are multiple devices for the mode in which a device is to be used (as precision trackpad or touch screen)

**Comment by gvkt** [comment]
> @gvkt Excellent! You are my hero. These kexts with my Info.plist mod solves multitouch issue of my ScreenPad! Multitouch is working on all of my devices now. Will do more test to see if there is any other problems.
> 
> One problem, which I think is already known, is that when the mouse cursor is left on the main touchscreen, when I touch on the screenpad, the cursor does not come to the point on the screenpad; instead, it mirrors the touch on the main touchscreen, and vice versa. Not sure if this required some major changes in VoodooI2C to solve this multiple touchscreens problem. The only way for me to get the cursor point move to the screenpad when the cursor is on the main touchscreen is by dragging the cursor with the trackpad to the screenpad in order to perform touch actions on the screenpad, and vice versa for the main touchscreen.

Glad it worked.

To solve the problem you have described, it would require your screenpad to work as a trackpad when the cursor is on the main screen and as a touch screen when the cursor is on the screenpad. This switch is not possible with the current architecture. Right now, you have the equivalent of dual touch screen external monitors attached to a Mac which will show the same behavior as you have observed.

**Comment by shiecldk** [comment]
@gvkt I think I don't need any fix to get the trackpad work on my laptop. It works OOB although I'm using polling SSDT now (made by atrslb). But I'm not sure if I got GPIO interest work. How do I check it?

**Comment by kprinssu** [comment]
@gvkt @shiecldk Can we stick to just addressing the original issue at hand to keep this thread tidy. 
Please use Gitter for support with pinning or anything else off-topic.

**Comment by shiecldk** [comment]
@kprinssu No problem. @gvkt We can continue this topic in my tonymacx86 UX582 thread.

**Comment by sqlsec** [comment]
@gvkt @shiecldk Today I tried to study the GPIO Pinning of this GDX1515 touchpad, and finally calculated that the GPIO Pin is `0x006D` and it works perfectly.

The main modifications are as follows：
![image](https://user-images.githubusercontent.com/25379234/146873221-7dcac882-73aa-4b64-9600-645a5b572dc5.png)
Use IORegistryExplorer to verify that it is successfully in GPIO interrupts mode
![image](https://user-images.githubusercontent.com/25379234/146873365-edcd83f9-f58a-41f9-98a0-e589e7625eca.png)

**Comment by gvkt** [comment]
@sqlsec Let us continue this with our discussion on the Voodoo thread at

https://www.tonymacx86.com/threads/voodooi2c-help-and-support.243378/page-144

Please post how you arrived at it in the above thread.

Good to know GPIO can work for GDX1515. The calculation will be different for CannolLake H CPUs and there might be a problem with the latter. If so, I can file a different report here. Thanks.

**Comment by narcyzzo** [comment]
hello @shiecldk can u look at my comment here? Need really help with fixing audio ! thank u

**Comment by kprinssu** [comment]
@narcyzzo Please keep the discussion to the topic on hand. This is not the place to ask for help, especially on a closed issue.
